
import type { Event, User, Society } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Alex Doe',
    email: 'student@example.com',
    avatarUrl: 'https://picsum.photos/seed/user1/100/100',
    role: 'student',
    interests: ['Tech', 'Music'],
    password: 'password',
  },
  {
    id: 'user-2',
    name: 'Music Society Admin',
    email: 'society@example.com',
    avatarUrl: 'https://picsum.photos/seed/user2/100/100',
    role: 'society_admin',
    societyIds: ['society-1'],
    password: 'password',
  },
  {
    id: 'user-3',
    name: 'Super Admin',
    email: 'admin@example.com',
    avatarUrl: 'https://picsum.photos/seed/user3/100/100',
    role: 'super_admin',
    password: 'password',
  }
];

export const mockSocieties: Society[] = [
  {
    id: 'society-1',
    name: 'Music Club',
    description: 'Campus music and concert society',
    logoUrl: 'https://picsum.photos/seed/society1/200/200',
    admins: ['user-2'],
  },
  {
    id: 'society-2',
    name: 'Tech Innovators',
    description: 'Technology and innovation society',
    logoUrl: 'https://picsum.photos/seed/society2/200/200',
    admins: ['user-2'],
  },
];

export const mockEvents: Event[] = [
  {
    id: 'event-1',
    title: 'Starlight Concert Series',
    description: 'Join us for an evening of live music under the stars. Featuring local bands and artists from our campus. Bring your friends and a blanket for a memorable night of tunes and good vibes. Food trucks will be available on site.',
    bannerUrl: 'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'music concert',
    startAt: '2024-10-26T19:00:00Z',
    endAt: '2024-10-26T23:00:00Z',
    venue: 'Main Quad',
    societyId: 'society-1',
    category: 'Music',
    isOnline: false,
    capacity: 200,
    isPaid: false,
    status: 'published',
    counters: {
      rsvpCount: 128,
      views: 450,
      checkIns: 0,
    },
  },
  {
    id: 'event-2',
    title: 'Codefest 2024 Hackathon',
    description: 'A 24-hour hackathon to build innovative projects. Prizes, food, and fun guaranteed. All skill levels welcome. Mentors from top tech companies will be present to guide you. Form teams or work solo!',
    bannerUrl: 'https://images.unsplash.com/photo-1542744095-291d1f67b221?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'tech workshop',
    startAt: '2024-11-02T10:00:00Z',
    endAt: '2024-11-03T10:00:00Z',
    venue: 'Engineering Building, Room 301',
    societyId: 'society-2',
    category: 'Tech',
    isOnline: false,
    capacity: 100,
    isPaid: false,
    status: 'published',
    counters: {
      rsvpCount: 76,
      views: 320,
      checkIns: 0,
    },
  },
  {
    id: 'event-3',
    title: 'Modern Art Vernissage',
    description: 'Explore the latest works from our talented student artists. A night of culture, conversation, and creativity. Light refreshments will be served. The theme for this exhibition is "Futurespectives".',
    bannerUrl: 'https://images.unsplash.com/photo-1506806732259-39c2d02a8e7f?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'art exhibition',
    startAt: '2024-11-05T18:00:00Z',
    endAt: '2024-11-05T21:00:00Z',
    venue: 'Fine Arts Gallery',
    societyId: 'society-1',
    category: 'Art',
    isOnline: false,
    capacity: 60,
    isPaid: false,
    status: 'published',
    counters: {
      rsvpCount: 45,
      views: 180,
      checkIns: 0,
    },
  },
  {
    id: 'event-4',
    title: 'Intramural Basketball Finals',
    description: 'The championship game is here! Come cheer for your favorite team as they battle for the trophy. Expect high-flying dunks and thrilling plays. Go Vipers!',
    bannerUrl: 'https://images.unsplash.com/photo-1515523110800-9415d13b84a8?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'sports game',
    startAt: '2024-11-08T20:00:00Z',
    endAt: '2024-11-08T22:00:00Z',
    venue: 'University Gymnasium',
    societyId: 'society-2',
    category: 'Sports',
    isOnline: false,
    capacity: 300,
    isPaid: false,
    status: 'published',
    counters: {
      rsvpCount: 250,
      views: 780,
      checkIns: 0,
    },
  },
  {
    id: 'event-5',
    title: 'Career Networking Night',
    description: 'Meet recruiters from top companies in various fields. A great opportunity to land an internship or job. Bring your resume and dress to impress. Open to all majors.',
    bannerUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'social event',
    startAt: '2024-11-12T17:00:00Z',
    endAt: '2024-11-12T20:00:00Z',
    venue: 'Student Union Ballroom',
    societyId: 'society-2',
    category: 'Social',
    isOnline: false,
    capacity: 250,
    isPaid: false,
    status: 'published',
    counters: {
      rsvpCount: 180,
      views: 560,
      checkIns: 0,
    },
  },
  {
    id: 'event-6',
    title: 'AI & The Future of Work',
    description: 'A keynote presentation by Dr. Evelyn Reed, a leading expert in artificial intelligence. Discover how AI is transforming industries and what it means for future careers. Q&A session to follow.',
    bannerUrl: 'https://images.unsplash.com/photo-1620712943543-95fc69614539?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'conference talk',
    startAt: '2024-11-15T16:00:00Z',
    endAt: '2024-11-15T18:00:00Z',
    venue: 'Science Auditorium',
    societyId: 'society-2',
    category: 'Conference',
    isOnline: false,
    capacity: 150,
    isPaid: false,
    status: 'published',
    counters: {
      rsvpCount: 95,
      views: 280,
      checkIns: 0,
    },
  },
  {
    id: 'event-7',
    title: 'Glow-in-the-Dark Party',
    description: 'End the semester with a bang! Wear your brightest neon and dance the night away. Free glow sticks and face paint for the first 100 attendees. Music by DJ Illuminate.',
    bannerUrl: 'https://images.unsplash.com/photo-1527489334187-34d38715845c?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'dj party',
    startAt: '2024-12-07T21:00:00Z',
    endAt: '2024-12-08T02:00:00Z',
    venue: 'Old Campus Hall',
    societyId: 'society-1',
    category: 'Party',
    isOnline: false,
    capacity: 400,
    isPaid: true,
    price: 10,
    status: 'published',
    counters: {
      rsvpCount: 300,
      views: 890,
      checkIns: 0,
    },
  },
  {
    id: 'event-8',
    title: 'Beginner Pottery Workshop',
    description: 'Get your hands dirty and learn the basics of pottery. We will guide you through creating your own unique piece, from throwing on the wheel to glazing. No experience necessary, all materials provided.',
    bannerUrl: 'https://images.unsplash.com/photo-1558942245-21c62f0135b0?q=80&w=1200&h=800&auto=format&fit=crop',
    imageHint: 'pottery workshop',
    startAt: '2024-11-20T14:00:00Z',
    endAt: '2024-11-20T17:00:00Z',
    venue: 'Craft Center',
    societyId: 'society-1',
    category: 'Workshop',
    isOnline: false,
    capacity: 25,
    isPaid: true,
    price: 15,
    status: 'published',
    counters: {
      rsvpCount: 20,
      views: 95,
      checkIns: 0,
    },
  },
];
