[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCPACZkQcMW9PxX5mkXm-wsYBlukOMAPIk"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "studio-827010330-91b76.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "studio-827010330-91b76"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "studio-827010330-91b76.appspot.com"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "271282670485"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:271282670485:web:49c4913d9655adfa55c49c"
  GOOGLE_GENAI_API_KEY = "AIzaSyBbRE4vqqiAxtCpvwaZgdYQAiiO9c4TyGk"
  GOOGLE_API_KEY = "AIzaSyBbRE4vqqiAxtCpvwaZgdYQAiiO9c4TyGk"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

